routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	// return view('welcome');
    return redirect(route('categories.index'));
});

Auth::routes();
Route::put('tickets/complete/{ticket}', 'TicketController@complete')->name('tickets.complete');
Route::put('tickets/reject/{ticket}', 'TicketController@reject')->name('tickets.reject');
// Route::get('/workers/{worker}','WorkerController@index')->name
Route::get('/home', 'WorkerController@index')->name('home');
Route::resource('workers', 'WorkerController');
Route::resource('categories', 'CategoryController');
Route::resource('tickets', 'TicketController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Worker.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Worker extends Model
{
    use SoftDeletes;
    protected $fillable = ['availability_id'];
	public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/WorkerController.php
<?php

namespace App\Http\Controllers;

use App\Worker;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Category;
use Str;

class WorkerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $category = Category::all();
        $workers = Worker::all()->where('category_id',$request->category);
        return view('workers.index')
        ->with('workers', $workers)
        ->with('category', $category);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Worker $worker)
    {
        $this->authorize('create', $worker);

        $categories = Category::all();
        return view('workers.create') -> with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Worker $worker)
    {
        // $this->authorize('create', $worker);
        //Flow
            // 1. validate each field
        $request->validate([
            'name'=> 'required|string',
            'price'=> 'required|numeric',
            'category'=> 'required',
            'introduction'=> 'required|string',
            'serial_number'=> 'required|string',
            'image'=> 'required|image|max:10000' //kb
            
        ]);
            // 2. save uploaded image
        $file = $request->file('image');
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $file_extension = $file->extension();
        $random_chars = Str::random(8);

        $new_file_name = date('Y-m-d-H-i-s'). "_" . $random_chars . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images',$new_file_name, 'public');
        // dd($new_file_name);
            // 3. get input values from form
        $name = $request->input('name');
        $price = $request->input('price');
        $category_id = $request->input('category');
        $introduction = $request->input('introduction');
        $serial_number = $request->input('serial_number');
        $image = $filepath;
            // 4. save the details to database
        $worker = new worker;
        $worker->name = $name;
        $worker->price = $price;
        $worker->introduction = $introduction;
        $worker->serial_number = $serial_number;
        $worker->image = $image;
        $worker->category_id = $category_id;
        $worker->save();
            // 5. redirect to worker created
        return redirect( route('workers.show', ['worker' => $worker->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function show(Worker $worker)
    {
     return view('workers.show')->with('worker', $worker);
     // $category = Category::all();
     // $worker = Worker::all();
     // return view('workers.show')
     // ->with('worker', $worker)
     // ->with('category', $category);
 }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function edit(Worker $worker)
    {
        // $this->authorize('update', $worker);

        $categories = Category::all();
        return view('workers.edit')
        ->with('worker', $worker)
        ->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Worker $worker)
    {
        // $this->authorize('update', $worker);
        //Flow
            // 1. validate each field
        $request->validate([
            'name'=> 'required|string',
            'price'=> 'required|numeric',
            'category'=> 'required',
            'introduction'=> 'required|string',
            'serial_number'=> 'required|string'
            
        ]);
            // 2. save uploaded image
        if (
            !$request->hasFile('image') && 
            $worker->name == $request->input('name') &&
            $worker->introduction == $request->input('introduction') &&
            $worker->serial_number == $request->input('serial_number') &&
            $worker->price == $request->input('price') &&
            $worker->category_id == $request->input('category')
        ) {
            $request->session()->flash('update_failed','Whoops! Something went wrong');
        }
        else{
            if($request->hasFile('image'))
            {
                $request->validate(
                    ['image' => 'required|image|max:10000']
                );

                // 2. save uploaded image
                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extension = $file->extension();
                $random_chars = Str::random(8);

                $new_file_name = date('Y-m-d-H-i-s'). "_" . $random_chars . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images',$new_file_name, 'public');

                // set new image path as new image value of worker
                $worker->image = $filepath;
            }

            $worker->name = $request->input('name');
            $worker->price = $request->input('price');
            $worker->category_id = $request->input('category');
            $worker->introduction = $request->input('introduction');
            $worker->serial_number = $request->input('serial_number');
            $worker->save();

            $request->session()->flash('update_success', 'Updated Worker!');
        }

        return redirect( route('workers.edit', ['worker' => $worker->id]));   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function destroy(Worker $worker)
    {
        // $this->authorize('delete', $worker);
        $worker->delete();
        // $request->session()->flash('destroy_success', 'Destroyed!');
        // return redirect(view('workers.index'));
        // return redirect(route('worker.index')) 
        // ->with('destroy_message', 'Worker Deleted');
        return redirect()->back()
        ->with('destroy_message', 'Worker Deleted');
    }

}

resources/views/workers/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto text-dark">
				<h3 class="text-center text-white">
					Hire a Worker
				</h3>
				<hr>
				<form method="post" action="{{ route('workers.store')}}" enctype="multipart/form-data">
					@csrf
					{{-- Input for name --}}
					<div class="form-group">
						<label for="name" class="text-white">Worker name:</label>
						<input type="text" name="name" class="form-control" id="name">
					</div>

					@if($errors->has('name'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif
										
					{{-- Input for price --}}
					<div class="form-group">
						<label for="price" class="text-white">Hiring price:</label>
						<input type="number" name="price" class="form-control" id="price">
					</div>

					@if($errors->has('price'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif

					{{-- Input category --}}
					<div class="form-group">
						<label for="category" class="text-white">Worker Category</label>
						<select class="form-control" id="category" name="category">
							@foreach($categories as $category)
							<option value="{{$category->id}}">{{$category->name}}</option>
							{{-- <option value="2">Fighting</option>
							<option value="3">Ghost</option>
							<option value="4">Fire</option>
							<option value="5">Psychic</option> --}}
							@endforeach
						</select>
					</div>

					@if($errors->has('category'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif

					{{-- Input for introduction --}}
					<div class="form-group">
						<label for="introduction" class="text-white">Worker introduction</label>
						<textarea name="introduction" class="form-control" id="introduction" cols="30" rows ="10"></textarea>
					</div>

					@if($errors->has('introduction'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif

					{{-- Input for introduction --}}
					<div class="form-group">
						<label for="serial_number" class="text-white">Worker serial number</label>
						<input type="number" name="serial_number" class="form-control" id="serial_number">
					</div>

					@if($errors->has('serial_number'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif

					{{-- Input for image --}}
					<div class="form-group">
						<label for="image" class="text-white">Worker Image:</label>
						<input type="file" name="image" class="form-control-file text-white id="image">
					</div>

					@if($errors->has('image'))
						<div class="alert alert-danger">
							<p>All Fields Required</p>
						</div>
					@endif

					<button class="btn btn-primary w-100">Add Worker</button>
				</form>
			</div>

			<div class="col-12 col-md-2 mx-auto">
				@if($errors->has('add_category'))
					<div class="alert alert-danger">
						<p>!ERROR!</p>
					</div>
				@elseif(Session::has('category_message'))
					<div class="alert alert-success">
						{{ Session::get ('category_message') }}
					</div>

				@endif

				<form method="post" action=" {{route('categories.store')}}">
					@csrf
					<div class="form-group">
					<label for="add-category" class="text-white"> Category Name:</label>
					<input type="text" name="category_name" id="category_name" class="form-control">
					<label for="add-category" class="text-white"> Category Description:</label>
					<textarea type="text" name="category_description" id="category_description" class="form-control" cols="30" rows ="10"></textarea>
					</div>

				<button class="btn btn-secondary w-100">Add Category</button>
				</form>
			</div>
		</div>

	</div>


@endsection

resources/views/workers/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center text-white">
				Hire a Worker
			</h3>
			<hr>
			@if(Session::has('update_failed'))
			<div class="alert alert-danger text-center">
				{{ Session::get('update_failed')}}
			</div>
			@elseif(Session::has('update_success'))
			<div class="alert alert-success text-center">
				{{ Session::get('update_success')}}
			</div>
			@endif
			<form method="post" action="{{ route('workers.update', ['worker' => $worker->id])}}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				{{-- Input for name --}}
				<div class="form-group">
					<label for="name" class="text-white">Worker name:</label>
					<input type="text" name="name" class="form-control" id="name" value="{{$worker->name}}">
				</div>

				@if($errors->has('name'))
				<div class="alert alert-danger">
					<p>All Fields Required</p>
				</div>
				@endif

				{{-- Input for price --}}
				<div class="form-group">
					<label for="price" class="text-white">Hiring price:</label>
					<input type="number" name="price" class="form-control" id="price" value="{{$worker->price}}">
				</div>

				@if($errors->has('price'))
				<div class="alert alert-danger">
					<p>All Fields Required</p>
				</div>
				@endif

				{{-- Input for price --}}
				<div class="form-group">
					<label for="price" class="text-white">Serial Number:</label>
					<input type="number" name="serial_number" class="form-control" id="serial_number" value="{{$worker->serial_number}}">
				</div>

				@if($errors->has('serial_number'))
				<div class="alert alert-danger">
					<p>All Fields Required</p>
				</div>
				@endif

				{{-- Input category --}}
				<div class="form-group">
					<label for="category" class="text-white">Worker Category</label>
					<select class="form-control" id="category" name="category">
						@foreach($categories as $category)
						<option 
						value="{{$category->id}}"
						@if($worker->category_id == $category->id)
						selected
						@endif
						>
						{{$category->name}}
					</option>
					@endforeach
				</select>
			</div>

			@if($errors->has('category'))
			<div class="alert alert-danger">
				<p>All Fields Required</p>
			</div>
			@endif

			{{-- Input for image --}}
			<div class="form-group">
				<label for="image" class="text-white">Worker Image:</label>
				<input type="file" name="image" class="form-control-file text-white" id="image">
			</div>

			@if($errors->has('image'))
			<div class="alert alert-danger">
				<p>All Fields Required</p>
			</div>
			@endif

			{{-- Input for introduction --}}
			<div class="form-group">
				<label for="introduction" class="text-white">Worker introduction</label>
				<textarea name="introduction" class="form-control" id="introduction" cols="30" rows ="10">{{$worker->introduction}}</textarea>
			</div>

			@if($errors->has('introduction'))
			<div class="alert alert-danger">
				<p>All Fields Required</p>
			</div>
			@endif

			<button class="btn btn-primary w-100">Edit Worker</button>

		</form>
	</div>
</div>		
</div>

@endsection

resources/views/workers/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="jumbotron bg-secondary">
				<h1 class="text-center text-white">
					{{-- Hire us! Hire us! --}}

					@if(count($workers))
					@foreach($workers as $worker)
					@endforeach

					@if($worker->category_id == 1)
					Strange jobs for your strange needs
					@elseif($worker->category_id == 2)
					On a cold rainy day I held your hand... and then time was up
					@elseif($worker->category_id == 3)
					Cooking the meals that your loved ones won't
					@elseif($worker->category_id == 4)
					Hire us or now or your friend will!
					@else
					The customer is mostly wrong
					@endif

					@else
					No Worker for this
					@endif
					
					{{-- {{dd($workers->category_id)}} --}}


					

					
				</h1>
			</div>
			
		</div>
	</div>
	@if(Session::has('destroy_message'))
	<div class="alert alert-warning text-center">
		{{ Session::get('destroy_message')}}
	</div>
	@endif
	<div class="row">
		<div class="col-12 col-md-10 ">
			<div class="row">
				{{-- {{dd($workers)}} --}}
				{{-- @foreach($category as $cat) --}}
				{{-- {{dd($cat->id)}} --}}
				
				@foreach($workers as $worker)
				{{-- {{dd($worker->category_id)}} --}}
				
				{{-- @if($worker->category_id == $cat->id) --}}

				<div class="col-12 col-md-4 col-lg-3 ">
					{{-- card start --}}
					<div class="card text-center bg-secondary match">
						<img src="{{url('/public/'.$worker->image)}}" class="card-img-top">
						{{-- body --}}
						<div class="card-body bg-dark text-white">
							<h2>{{$worker->name}}</h2>
							<p class="card-text">
								<strong>
									&#8369; {{$worker->price}}
								</strong>
							</p>
							<p class="card-text ">
								{{-- {{$worker->availability_id}} --}}
								@if($worker->availability_id == 1)
								<p class="text-success">Available</p>
								@else
								<p class="text-danger">Unavailable</p>
								@endif
							</p>
							<p class="card-text	bg-secondary text-light ">
								{{$worker->introduction}}
							</p>
						</div>
						{{-- footer --}}
						<div class="card-foot bg-dark">
							@if(Auth::check())
							@if(Auth::user()->role_id==1)
							<a href="{{ route('workers.show', ['worker' => $worker->id] )}}" class="w-100 btn btn-info my-1"> View</a>
							{{-- @can('isAdmin') --}}
							<a href="{{ route('workers.edit', ['worker' => $worker->id] )}}" class="w-100 btn btn-primary my-1"> Edit</a>
							<form action="{{route('workers.destroy', ['worker' => $worker->id])}}" method="post">
								@csrf
								@method('DELETE')
								<button class="btn btn-danger w-100 my-1">Delete</button>
							</form>
							@endif
							
							{{-- {{dd($worker->availability_id)}} --}}
							@if($worker->availability_id == 1 && Auth::user()->role_id!=1)
							<form action="{{route('tickets.store')}}" method="post">
								<div class="form-group my-1">
									@csrf
									<input type="hidden" name="id" value="{{$worker->id}}">
									<h6 class="text-light m-0"> Duration (Hours)</h6>
									<input class="text-center text-secondary" type="number" name="duration" value="1" min="1">
								</div>
								<button type="submit" class="btn btn-success w-100"> Request
								</button>
							</form>
							@endif
							@endif
							{{-- @endcan --}}
						</div>
					</div>
					{{-- end card --}}
				</div>
			{{-- 	@else
				<div class="jumbotron">
					<h1 class="text-center text-dark">
						No one.
					</h1>
				</div> --}}
				{{-- @endif --}}
				@endforeach
				{{-- @endforeach --}}
			</div>
		</div>
	</div> {{-- end row --}}
</div>

@endsection

resources/views/workers/show.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center text-light">
				See our Workers!
			</h3>
			<hr>
			<div class="card text-center bg-secondary">
				<img src="{{url('/public/'.$worker->image)}}" class="card-img-top">
				<div class="card-body bg-dark text-white">
					<h2>{{$worker->name}}</h2>
					<p class="card-text">
						<strong>
							&#8369; {{$worker->price}}
						</strong>
					</p>
					<p class="card-text	">
						{{$worker->introduction}}
					</p>
				</div>
				<div class="card-foot bg-dark">
					
					<a href="{{ route('workers.create') }}" class="w-100 btn btn-info my-1"> Add More</a>
					{{-- @can('isAdmin') --}}
					<a href="{{ route('workers.edit', ['worker' => $worker->id] )}}" class="w-100 btn btn-primary my-1"> Edit</a>
					<form action="{{route('workers.destroy', ['worker' => $worker->id])}}" method="POST">
						@csrf
						@method('DELETE')
						<button class="btn btn-danger w-100 my-1">Delete</button>
					</form>
					{{-- @endcan --}}
				</div>
			</div>
		</div>
	</div>
</div>

@endsection