routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	// return view('welcome');
    return redirect(route('categories.index'));
});

Auth::routes();
Route::put('tickets/complete/{ticket}', 'TicketController@complete')->name('tickets.complete');
Route::put('tickets/reject/{ticket}', 'TicketController@reject')->name('tickets.reject');
// Route::get('/workers/{worker}','WorkerController@index')->name
Route::get('/home', 'WorkerController@index')->name('home');
Route::resource('workers', 'WorkerController');
Route::resource('categories', 'CategoryController');
Route::resource('tickets', 'TicketController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ticket extends Model
{
    use SoftDeletes;
    public function status()
    {
        return $this->belongsTo('App\Status');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function workers()
    {
        return $this->belongsToMany('App\Worker', 'ticket_product')
            ->withPivot('duration')
            ->withTimestamps();
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Ticket;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Str;
use Session;
use App\Worker;
use App\Status;
use App\User;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user, Ticket $ticket)
    {
        $this->authorize('view', $ticket);
        // $this->authorize('view', $user);

        if(Auth::user()->role_id==1)
        {
            $statuses = Status::all();
            $tickets = Ticket::all();
            
        }
        else
        {
            $statuses = Status::all()->where('user_id', Auth::user()->id);
            $tickets = Ticket::all()->where('user_id', Auth::user()->id);
        }

        return view('tickets.index')
        ->with('tickets', $tickets)
        ->with('statuses', $statuses);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         // Flow
            // 1. create an entry in tickets table with he following attributes
                // reference_number 
                // status_id
                // user_id
        $ticket = new Ticket;
        // $ticket_number = Auth::user()->id . Str::random(5) . time();
        // dd(Auth::user());
        $reference_number = Auth::user()->name . Str::random(5). '1z' . time() . '2D\/mb';
        $user_id = Auth::user()->id;
        // $user_id = 1;

        $ticket->reference_number = $reference_number;
        $ticket->user_id = $user_id;
        $ticket->save();  
        
        $ticket->workers()->attach(
            $request->input('id'), 
            [
                'duration' => $request->input('duration'),
                'worker_id' => $request->input('id'),
                'ticket_id' => $ticket->id
            ]
        );
        // dd($ticket->workers);

        return redirect(route('tickets.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket, Worker $worker)
    {
        // dd($ticket->workers);

        $ticket->status_id = 2;
        $ticket->save();
        // dd($ticket->workers[0]->id);
        // foreach ($ticket->workers as $ticketworker) {
        //     // dd($ticketworkers);
        //     $ticketworker->update([
        //         'availability_id' => 2
        //     ]);
        //     // dd($ticketworkers->availability_id);
        // }


        // $worker->availability_id=2;
            // $worker->save();
        $ticket->workers[0]->where('id', $ticket->workers[0]->id)->update([
            'availability_id' => 2
        ]);

        return redirect(route('tickets.index'))
        ->with('updated_ticket', $ticket->id);
    }

    public function complete(Request $request, Ticket $ticket, Worker $worker)
    {
        $ticket->status_id = 3;
        $ticket->save();
        $ticket->workers[0]->where('id', $ticket->workers[0]->id)->update([
            'availability_id' => 1
        ]);
        // $ticket->workers[0]->availability_id
        // $ticket->workers[0]->save();

        // foreach ($ticket->workers as $ticketworker) {
        //     // dd($ticketworkers);
        //     $ticketworker->update([
        //         'availability_id' => 1
        //     ]);
        // }
        // $worker->save();

        return redirect(route('tickets.index'))
        ->with('updated_ticket', $ticket->id);
    }

    public function reject(Request $request, Ticket $ticket, Worker $worker)
    {
        $ticket->status_id = 4;
        $ticket->save();
        $ticket->workers[0]->where('id', $ticket->workers[0]->id)->update([
            'availability_id' => 1
        ]);

        return redirect(route('tickets.index'))
        ->with('updated_ticket', $ticket->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        $ticket -> delete();
        return redirect(route('tickets.index')); 
    }
}

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	{{-- <div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<div class="row">
				<h2>My Pending Requests</h2>
				<table class="table table-dark">
					<thead>
						<tr>
							<th scope="col">Product Line</th>
							<th scope="col">Ref. No.</th>
							<th scope="col">Borrow Date</th>
							<th scope="col">Return Date</th>
							<th scope="col">Request Date</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($tickets as $ticket)
						<tr>
							<td>{{$ticket->id}}</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>
								<button data-id="36" class="btn btn-warning cancelBtns">Cancel</button>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				<h2>My Approved Requests</h2>
				<table class="table table-dark">
					<thead>
						<tr>
							<th scope="col">Ref. No.</th>
							<th scope="col">Asset Serial #</th>
							<th scope="col">Borrow Date</th>
							<th scope="col">Return Date</th>
							<th scope="col">Approved On</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
				<h2>My Completed Requests</h2>
				<table class="table table-dark">
					<thead>
						<tr>
							<th scope="col">Ref. No.</th>
							<th scope="col">Asset Serial #</th>
							<th scope="col">Borrow Date</th>
							<th scope="col">Return Date</th>
							<th scope="col">Status</th>
							<th scope="col">Completed On</th>
						</tr>
					</thead>
					<tbody id="completedTransactions">
						<tr>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
							<td>TEST</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div> --}}
	<div class="row">
		<div class="col-lg-8 offset-lg-2">
			<h2 class="text-white"> <i class="fas fa-ticket-alt"></i> Ticket Pending</h2>

			<table class="table table-dark">
				<thead>
					<tr>
						<th scope="col">User</th>
						<th scope="col">Category</th>
						<th scope="col">Worker</th>
						<th scope="col">Duration</th>
						<th scope="col">Confirmation</th>
					</tr>
				</thead>

				<tbody>
					@foreach($tickets as $ticket)
					@if($ticket->status->name == 'pending')
					<tr>
						<td>{{$ticket->user->name}}</td>
						
						@foreach($ticket->workers as $ticketworkers)
						<td>{{$ticketworkers->category->name}}</td>
						<td>{{$ticketworkers->name}}</td>
						<td>{{$ticketworkers->pivot->duration}}</td>
						@endforeach
						<td>
							@if(Auth::user()->role_id==1)
							<form action="{{route('tickets.update',['ticket' => $ticket->id]) }}" method="post">
								@csrf
								@method('PUT')
								
								<input type="hidden" name="status" value="2">
								<button class="btn btn-success approveBtns">Approve</button>
							</form>
							<form action="{{route('tickets.reject',['ticket' => $ticket->id]) }}" method="post">
								@csrf
								@method('PUT')
								<input type="hidden" name="status" value="4">
								<button class="btn btn-danger rejectBtns">Reject</button>
							</form>
							@else
							<form action="{{route('tickets.destroy',['ticket' => $ticket->id]) }}" method="post">
								@csrf
								@method('DELETE')
								<button class="btn btn-warning rejectBtns">Cancel</button>
							</form>
							@endif
						</td>
					</tr>
					@endif
					@endforeach
				</tbody>                    
			</table>
			<hr>
			<h2 class="text-white"> <i class="fas fa-check-square"></i> Approved Transactions</h2>
			<table class="table table-dark">
				<thead>
					<tr>
						<th scope="col">User</th>
						<th scope="col">Reference Number</th>
						<th scope="col">Worker</th>
						<th scope="col">Duration</th>
						<th scope="col">Approved On</th>
						@if(Auth::user()->role_id==1)
						<th scope="col">Actions</th>
						@endif
					</tr>
				</thead>

				<tbody id="approvedTransactions">
					@foreach($tickets as $ticket)
					@if($ticket->status->name == 'approved')
					<tr>
						<td>{{$ticket->user->name}}</td>
						<td>{{($ticket->reference_number) }}</td>
						@foreach($ticket->workers as $ticketworkers)
						<td>{{$ticketworkers->name}}</td>
						<td>{{$ticketworkers->pivot->duration}}</td>
						@endforeach
						<td>{{$ticket->updated_at}}</td>
						@if(Auth::check())
						@if(Auth::user()->role_id==1)
						<td>
							<form action="{{route('tickets.complete',['ticket' => $ticket->id]) }}" method="post">
								@csrf
								@method('PUT')
								<input type="hidden" name="status" value="3">
								<button class="btn btn-success returnBtns">Hours Done</button>
							</form>
						</td>
						@endif
						@endif
					</tr>
					@endif
					@endforeach
				</tbody>                    
			</table>

			<hr>

			<h2 class="text-white"> <i class="fas fa-clipboard-list"></i> Completed Transactions</h2>
			<table class="table table-dark">
				<thead>
					<tr>
						<th scope="col">User</th>
						<th scope="col">Reference Number</th>
						<th scope="col">Worker</th>
						<th scope="col">Duration</th>
						<th scope="col">Status</th>
						<th scope="col">Completed On</th>
					</tr>
				</thead>

				<tbody id="completedTransactions">
					@foreach($tickets as $ticket)
					@if($ticket->status->name == 'completed' || $ticket->status->name == 'rejected')
					<tr>
						<td>{{$ticket->user->name}}</td>
						<td>{{($ticket->reference_number) }}</td>
						@foreach($ticket->workers as $ticketworkers)
						<td>{{$ticketworkers->name}}</td>
						<td>{{$ticketworkers->pivot->duration}}</td>
						@endforeach
						<td>{{$ticket->status->name}}</td>
						<td>{{$ticket->updated_at}}</td>
					</tr>
					@endif
					@endforeach
				</tbody>                    
			</table>
		</div>
	</div>

</div>

</div>
@endsection