routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	// return view('welcome');
    return redirect(route('categories.index'));
});

Auth::routes();
Route::put('tickets/complete/{ticket}', 'TicketController@complete')->name('tickets.complete');
Route::put('tickets/reject/{ticket}', 'TicketController@reject')->name('tickets.reject');
// Route::get('/workers/{worker}','WorkerController@index')->name
Route::get('/home', 'WorkerController@index')->name('home');
Route::resource('workers', 'WorkerController');
Route::resource('categories', 'CategoryController');
Route::resource('tickets', 'TicketController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;
    public function products(){
    	return $this->hasMany('App\Worker');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category)
    {
        $request->validate([
            'category_name' => 'required|unique:categories,name',
            'category_description' => 'required|string'
        ]);

        $name = $request->input('category_name');
        $description = $request->input('category_description');


        $new_category = new Category;
        $new_category->name = $name;
        $new_category->description = $description;

        $new_category->save(); //save to database
        // dd($new_category);

        $request->session()->flash('category_message', 'Category successfully added!');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categories.show')->with('category', $category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.edit')
        ->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {   

        $this->authorize('update', $category);
        // dd($category);
        $request->validate([
            'category_name' => 'required|unique:categories,name',
            'category_description' => 'required|string'
        ]);

        // $request->session()->flash('update_failed','Whoops! Nothing Changed');

        $category->name = $request->input('category_name');
        $category->description = $request->input('category_description');
        $category->save();   

        $request->session()->flash('update_success', 'Updated Category!');
        return redirect( route('categories.edit', ['category' => $category->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //just a comment
        $category->delete();
        return redirect(route('categories.index'))
        ->with('destroy_message', 'Category Deleted');
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center text-white">
				Edit this Category
			</h3>
			<hr>
			@if($errors->has('category_name'))
			<div class="alert alert-warning text-center m-0">
				<p>Name needs to be unique!</p>
			</div>
			@endif
			@if(Session::has('update_success'))
				<div class="alert alert-success text-center">
					{{ Session::get('update_success')}}
				</div>
				@endif
			{{-- @if(Session::has('update_failed'))
			<div class="alert alert-danger text-center">
				{{ Session::get('update_failed')}}
			</div>
			@elseif(Session::has('update_success'))
			<div class="alert alert-success text-center">
				{{ Session::get('update_success')}}
			</div>
			@endif --}}
			<form method="post" action="{{ route('categories.update', ['category' => $category->id])}}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				{{-- Input for name --}}
				<div class="form-group">
					<label for="name" class="text-white">Category name:</label>
					<input type="text" name="category_name" class="form-control" id="name" value="{{$category->name}}">
				</div>

				@if($errors->has('name'))
				<div class="alert alert-danger">
					<p>All Fields Required</p>
				</div>
				@endif


				{{-- Input for description --}}
				<div class="form-group">
					<label for="description" class="text-white">Category description</label>
					<textarea name="category_description" class="form-control" id="description" cols="30" rows ="10">{{$category->description}}
					</textarea>
				</div>

				@if($errors->has('description'))
				<div class="alert alert-danger">
					<p>All Fields Required</p>
				</div>
				@endif

				

				<button class="btn btn-primary w-100">Edit category</button>
			</form>
		</div>
	</div>		
</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="jumbotron bg-secondary">
				<h1 class="text-center text-white">
					Doing it for the money not love.
				</h1>
			</div>
		</div>
	</div>
	@if(Session::has('destroy_message'))
	<div class="alert alert-warning text-center">
		{{ Session::get('destroy_message')}}
	</div>
	@endif
	<div class="row">
		<div class="col-12 col-md-12 mx-auto">
			<div class="row">
				@foreach($categories as $category)
				<div class="col-12 col-md-4 mx-auto">
					<div class="card text-center m-2 bg-secondary ">
						<div class="card-header"  id="headingOne">
							<h5 class="mb-0">
								{{-- <button class="btn btn-link" data-toggle="" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"> --}}
									<p class="text-dark bg-white p-1 m-0">{{$category->name}}</p>
								{{-- </button> --}}
							</h5>
							<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
								<div class="card-body text-white match">
									{{$category->description}}
								</div>
							</div>
						</div>
						{{-- Buttons --}}
						<div class="card-footer">
							<a href="{{ route('workers.index', ['category'=>$category->id])}}" class="btn btn-success w-100"> View</a>
							@if(Auth::check())
							@if(Auth::user()->role_id==1)
							<a href="{{ route('categories.edit', ['category' => $category->id] )}}" class="btn btn-primary w-100"> Edit</a>
							<form action="{{route('categories.destroy', ['category' => $category->id])}}" method="post">
								@csrf
								@method('DELETE')
								<button class="btn btn-danger w-100 ">Delete</button>
							</form>
							@endif
							@endif	
						</div>
						{{-- end buttons a--}}
					</div>
				</div>
				@endforeach	
			</div>
		</div>
	</div> {{-- end row --}}
</div>

@endsection


{{-- @foreach($categories as $category) --}}
{{-- <div class="col-12 col-md-12 m-2"> --}}
	{{-- card start --}}
	{{-- <div class="card text-center bg-secondary"> --}}
		{{-- body --}}
		{{-- <div class="card-body bg-dark text-white"> --}}
			{{-- <h2>{{$category->name}}</h2> --}}
			{{-- <p class="card-text	"> --}}
				{{-- {{$category->description}} --}}
			{{-- </p> --}}
		{{-- </div> --}}
		{{-- footer --}}
		{{-- <div class="card-foot bg-dark"> --}}

			{{-- @can('isAdmin') --}}
			{{-- <a href="{{ route('categories.edit', ['category' => $category->id] )}}" class="btn btn-primary w-10 float-right"> Edit</a> --}}
			{{-- <form action="{{route('categories.destroy', ['category' => $category->id])}}" method="post"> --}}
				{{-- @csrf --}}
				{{-- @method('DELETE') --}}
				{{-- <button class="btn btn-danger w-10 float-right">Delete</button> --}}
			{{-- </form> --}}
			{{-- @endcan --}}
		{{-- </div> --}}
	{{-- </div> --}}
	{{-- end card --}}
{{-- </div> --}}
{{-- @endforeach --}}